# Generated by Django 6.0.7 on 2026-09-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referral Code'),
        ),
    ]
