# Generated by Django 6.0.7 on 2026-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='tier_required',
            field=models.CharField(choices=[('standard', 'Standard Academy (₹5,000)'), ('gold_strategy', 'Gold Strategy + Indicator (₹10,000)')], default='standard', help_text='Subscription tier required to unlock', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='badge',
            field=models.CharField(blank=True, help_text='e.g., Special Indicator ₹10,000, F&O, Equity', max_length=50),
        ),
    ]
