# Generated by Django 6.0.7 on 2026-09-17 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_subcategory_tier_required_alter_subcategory_badge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('announcements', '📢 Announcements (Mentor Only)'), ('setups', '📊 Trade Setups'), ('general', '💬 General Discussion'), ('trading', '🎓 Trading Discussion')], default='general', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='message-square', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_mentor_only_posting', models.BooleanField(default=False, help_text='Only staff/mentors can post in this channel')),
            ],
            options={
                'verbose_name': 'Community Channel',
                'verbose_name_plural': 'Community Channels',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_mentor_post', models.BooleanField(default=False)),
                ('is_trade_setup', models.BooleanField(default=False)),
                ('setup_symbol', models.CharField(blank=True, help_text='e.g. XAUUSD BUY SETUP', max_length=100)),
                ('setup_entry', models.CharField(blank=True, max_length=100)),
                ('setup_sl', models.CharField(blank=True, max_length=100)),
                ('setup_tp1', models.CharField(blank=True, max_length=100)),
                ('setup_tp2', models.CharField(blank=True, max_length=100)),
                ('setup_chart_text', models.TextField(blank=True, help_text='Chart analysis notes')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='courses.communitychannel')),
                ('parent_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='courses.communitymessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Message',
                'verbose_name_plural': 'Community Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
