# Generated by Django 6.0.7 on 2026-09-23 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lecture_and_remove_demo_videos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.CharField(choices=[('indian_market', 'Indian Market Mastery'), ('forex_gold', 'Forex & Gold Mastery')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='position',
            field=models.PositiveIntegerField(default=1, help_text='Display order within the course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_path',
            field=models.CharField(help_text='Path in Supabase Storage private bucket', max_length=500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='badge',
            field=models.CharField(blank=True, help_text='e.g., Special Indicator, Price Action, Equity', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='tier_required',
            field=models.CharField(choices=[('standard', 'Indian Market Foundation (₹3,999)'), ('gold_strategy', 'Forex Gold Mastery (₹9,999)')], default='standard', help_text='Subscription tier required to unlock', max_length=50),
        ),
        migrations.AlterModelTable(
            name='lecture',
            table='courses_lecture',
        ),
        migrations.CreateModel(
            name='LectureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecture Progress',
                'verbose_name_plural': 'Lecture Progress',
                'db_table': 'courses_lectureprogress',
                'ordering': ['-last_watched_at'],
                'unique_together': {('user', 'lecture')},
            },
        ),
    ]
