# Generated by Django 6.0.7 on 2026-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('standard', 'Standard Academy (₹5,000)'), ('gold_strategy', 'Forex Gold Strategy + Indicator (₹10,000)'), ('combo', 'Combined All-Access Bundle (₹12,500)')], db_index=True, default='combo', max_length=50),
        ),
    ]
