# Generated by Django 6.0.7 on 2026-09-21 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_plan_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=3999.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(default='Complete Trader (12 Months)', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Indian Market Foundation (₹3,999)'), ('pro', 'Forex Gold Mastery (₹9,999)'), ('elite', 'Complete Trader (₹11,999)'), ('standard', 'Indian Market Foundation (₹3,999)'), ('gold_strategy', 'Forex Gold Mastery (₹9,999)'), ('combo', 'Complete Trader (₹11,999)')], db_index=True, default='elite', max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(db_index=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='created', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('short_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
