# Generated by Django 6.0.7 on 2026-09-21 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_manualpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='user_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('subscription_activated', 'Subscription Activated'), ('info', 'Information')], default='info', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='/dashboard/', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'db_table': 'user_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
